# Generated by Django 4.1.2 on 2023-01-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_course_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_tg',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_vk',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
