# Generated by Django 4.1.2 on 2023-01-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_author_rating_count_user_author_rating_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
