# Generated by Django 4.1.2 on 2023-01-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_contact_email_alter_user_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_tg',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_vk',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
