# Generated by Django 4.1.2 on 2023-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_contact_phone_alter_user_contact_tg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
