# Generated by Django 4.1.2 on 2022-11-15 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('difficulty_stage_of_study', models.CharField(choices=[('N', 'None'), ('S', 'School'), ('C', 'College'), ('B', "bachelor's degree"), ('M', "master's degree"), ('PG', 'postgraduate study')], default='N', max_length=2)),
                ('difficulty_course_of_study', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('A', 'accepting applications'), ('P', 'in progress'), ('C', 'completed')], max_length=1)),
                ('time_rate', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('accuracy_rate', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_accepting_applications_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 18, 37, 41, 401740))),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='C:\\Users\\Vanek\\Desktop\\Assistance_Platform_backend\\media\\tasks/task_files')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
    ]
