# Generated by Django 4.1.2 on 2022-11-22 00:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='applicants',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 3, 0, 1, 37885)),
        ),
    ]
