# Generated by Django 4.1.2 on 2023-01-03 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubject',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasktag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 10, 6, 24, 55, 855854)),
        ),
    ]
