# Generated by Django 4.1.2 on 2023-01-03 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_subject_name_tasksubject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 10, 19, 32, 21, 213966)),
        ),
    ]
