# Generated by Django 4.1.2 on 2022-11-22 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_applicants_alter_task_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 3, 0, 48, 912995)),
        ),
    ]
