# Generated by Django 4.1.2 on 2023-01-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksubject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tasktag',
            options={'ordering': ['name']},
        ),
    ]
