# Generated by Django 4.1.2 on 2023-01-03 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_closed_at_alter_task_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'accepted'), ('R', 'rejected'), ('S', 'sent')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 23, 2, 0, 215685)),
        ),
    ]
