# Generated by Django 4.1.2 on 2023-01-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasksubject_options_alter_tasktag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfile',
            name='filename',
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='tasks/task_files'),
        ),
    ]
