# Generated by Django 4.1.2 on 2023-01-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_taskfile_filename_alter_taskfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='difficulty_course_of_study',
            new_name='course_of_study',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='difficulty_stage_of_study',
            new_name='stage_of_study',
        ),
    ]
