# Generated by Django 4.1.2 on 2023-01-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_application_status_alter_task_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
