# Generated by Django 4.1.2 on 2023-01-05 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_application_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='accuracy_rate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_rate',
        ),
        migrations.AddField(
            model_name='task',
            name='author_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='task',
            name='doer_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='task',
            name='review_on_author',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='review_on_doer',
            field=models.TextField(blank=True),
        ),
    ]
