# Generated by Django 4.1.2 on 2023-01-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_accuracy_rate_remove_task_time_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubject',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
