# Generated by Django 4.1.2 on 2023-01-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tasksubject_name_alter_tasktag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
